import Navbar from '@/components/Navbar/content'
import "../tailwind.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        < styles />
        <Navbar />

        {children}
      </body>
    </html>
  );
}
