import { Aside } from '@/components/Aside'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        < styles />
        <Aside />
        {children}
      </body>
    </html>
  );
}
